drop PR number writing, fail on empty used headers

diff --git a/.github/workflows/check-build-test.yml b/.github/workflows/check-build-test.yml
--- a/.github/workflows/check-build-test.yml
+++ b/.github/workflows/check-build-test.yml
@@ -110,11 +110,9 @@ jobs:
           cat static-analysis/clang-tidy.txt | python3 -m clang_tidy_converter sq > static-analysis/clang-tidy.json
         shell: bash
       - name: Report unused files
-        run: cat static-analysis/unused-headers.txt
-      - name: Save PR number to file
         run: |
-          echo ${{ github.event.number }} > static-analysis/PR_NUMBER.txt
-          cat static-analysis/PR_NUMBER.txt
+          cat static-analysis/unused-headers.txt
+          [ -s static-analysis/used-headers.txt ] || { echo "error: no used headers found"; exit 1 }
       - name: Store static analysis results
         uses: actions/upload-artifact@v4
         if: always()
